#1. Create a null vector of size 10 but the fifth value which is 1.

In [12]:
import numpy as np 
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#2. Create a vector with values ranging from 10 to 49.

In [13]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#3. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [26]:
x=np.array([1,2,0,0,4,0])
print("indices of non-zero elements are:",np.nonzero(x))

indices of non-zero elements are: (array([0, 1, 4], dtype=int64),)


#5. Create a 10x10 array with random values and find the minimum and maximum values.

In [77]:
import random
random.seed(10)
x=np.random.random(size=(10,10))
print("Minimum vales:",x.min())
print("Maximum values:",x.max())
print(x)


Minimum vales: 0.0017622460817506846
Maximum values: 0.9834629996330242
[[0.44008267 0.61547397 0.18299672 0.64802661 0.2177452  0.57906615
  0.80276288 0.70064298 0.5818409  0.41014284]
 [0.25117317 0.17145884 0.48987229 0.78005438 0.29402998 0.82135818
  0.50369688 0.02389083 0.54648941 0.31478633]
 [0.55222043 0.42309481 0.21427638 0.6396628  0.93636771 0.5975111
  0.14969288 0.40632628 0.50898899 0.01470423]
 [0.84114966 0.44772352 0.39778651 0.47259367 0.07822464 0.31026269
  0.51926964 0.36734163 0.81942951 0.90201428]
 [0.84378802 0.56394633 0.65960802 0.86744749 0.4892273  0.91139153
  0.09248642 0.56988145 0.46507358 0.86708875]
 [0.31835627 0.03572087 0.38632562 0.79388606 0.87984908 0.54066201
  0.70736704 0.36235083 0.65222529 0.68888939]
 [0.47304041 0.11292765 0.58952359 0.81755675 0.24697563 0.28796746
  0.7718215  0.80179455 0.88842742 0.74519835]
 [0.6845665  0.5039969  0.17778369 0.30775871 0.53066174 0.74794765
  0.08138968 0.9418501  0.97251622 0.07001332]
 [0.85006

#6. Create a random vector of size 30 and find the mean value.

In [82]:
arr=np.random.random((5,6))
Mean_value_of_the_matrix=np.mean(arr)
print("mean:",Mean_value_of_the_matrix)


mean: 0.5061633093970229
